name: Scraper

on:
  workflow_dispatch:  # Only triggered by dispatch (from scheduled-trigger or manually)
concurrency:
  group: tieba-talk-serial-global     # any constant string => single global queue for workflow
  cancel-in-progress: false    # do NOT cancel; queue instead
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Private Repo
        env:
          PAT_GITHUB: ${{ secrets.PAT_GITHUB }}
        run: |
          git clone https://x-access-token:${PAT_GITHUB}@github.com/iamCristYE/Tieba-Talk.git
          cd Tieba-Talk

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install aiotieba
        run: |
          pip install requests
          # pip install aiotieba
          git clone https://github.com/iamcristye/aiotieba/
          cd aiotieba
          pip install -e .
          
      - name: Install Dependencies
        run: |
          cd Tieba-Talk
          pip install requests
          # pip install aiotieba


      - name: Run Scraper
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID_TIEBA: ${{ secrets.TELEGRAM_CHAT_ID_TIEBA }}
          TELEGRAM_CHAT_ID_TALK: ${{ secrets.TELEGRAM_CHAT_ID_TALK }}
        run: |
          cd Tieba-Talk
          python main.py

      - name: Commit and Push Changes
        run: |
          cd Tieba-Talk
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data.json
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Update sent IDs - $(date)"
            git push
            echo "Changes committed and pushed."
          else
            echo "No changes to commit."
          fi
          
      - name: Poll for condition and run task
        run: |
          echo "$(date '+%Y-%m-%d %H:%M:%S')"
          echo "Triggered scraper-runner workflow. Sleeping 600s..."
          sleep 600
          echo "$(date '+%Y-%m-%d %H:%M:%S')"

          curl -X POST \
              -H "Authorization: Bearer ${{ secrets.PAT_GITHUB }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/iamcristye/Tieba-Talk-Public/actions/workflows/scraper-runner.yml/dispatches \
              -d '{"ref":"main"}'
 
        env:
          PAT_GITHUB: ${{ secrets.PAT_GITHUB }}
